<a href="https://colab.research.google.com/github/alunkom/PyTorch/blob/main/00_PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## << 00 . PyTorch Fundamentals >>


# Import Libraries 

In [3]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

1.13.1+cu116


## Introduction Tensors

## creating tensors

 'Image to declare what is exaly are Scalar AND Vector AND MATRIX'
Link : https://hadrienj.github.io/assets/images/2.1/scalar-vector-matrix-tensor.png

In [7]:
 # scalar 
 scalar = torch.tensor(7)
 scalar

tensor(7)

In [8]:
scalar.ndim

0

In [10]:
# Get tensor back as Python int
scalar.item()

7

In [11]:
# Vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [21]:
# Matrix
MATRIX = torch.tensor([[7, 8,3]
                      ,
                      [9 ,10,5]])
MATRIX

tensor([[ 7,  8,  3],
        [ 9, 10,  5]])

In [44]:
# Shape of MATRIX
MATRIX.shape
# دو بعد که هر کدوم 3 تا المان دارن 

torch.Size([2, 3])

In [24]:
# تعداد بعد ها 
MATRIX.ndim

2

In [28]:
# عنصر خاص از متغیر MATRIX 
MATRIX[0][1]
# بعد اول ، عنصر دوم :)

tensor(8)

In [43]:
# TENSOR
# تنژور 
TENSOR  = torch.tensor([
    [
        [1,2,3], [4,5,6], [7, 8, 9]
                         ]
                        ])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [30]:
# ndim 
TENSOR.ndim

3

In [31]:
TENSOR.shape

torch.Size([1, 3, 3])

تو بالا اولین عدد که میشه یک نشون میده ما یه فضا داریم (نشون دهنده ی اولین براکت ماست ) 
دومی ، عدد سه نشون میده 3 تا بعد داریم .
و سومی نشون بده هر کدوم از اون بعدا 3 تا المان دارن 

In [42]:
# تو نشون دادن براکت اولی از یک شروع میشه
# ولی موقع فراخوانی باید از صفر شروع کنیم :)
# میفهمم یکم عجیبه اما ترس نداره که یه گوگل کردن
# جیرینگی کارمونو راه میندازه:)
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
TENSOR[0][2]

tensor([7, 8, 9])

In [40]:
TENSOR[0][0:2]

tensor([[1, 2, 3],
        [4, 5, 6]])