<a href="https://colab.research.google.com/github/alunkom/PyTorch/blob/main/00_PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## << 00 . PyTorch Fundamentals >>


# Import Libraries 

In [3]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

1.13.1+cu116


## Introduction Tensors

Resorce : https://www.learnpytorch.io/00_pytorch_fundamentals/

## creating tensors

 'Image to declare what is exaly are Scalar AND Vector AND MATRIX'
Link : https://hadrienj.github.io/assets/images/2.1/scalar-vector-matrix-tensor.png

In [7]:
 # scalar 
 scalar = torch.tensor(7)
 scalar

tensor(7)

In [8]:
scalar.ndim

0

In [10]:
# Get tensor back as Python int
scalar.item()

7

In [11]:
# Vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [65]:
vector.dtype

torch.int64

In [66]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [21]:
# Matrix
MATRIX = torch.tensor([[7, 8,3]
                      ,
                      [9 ,10,5]])
MATRIX

tensor([[ 7,  8,  3],
        [ 9, 10,  5]])

In [44]:
# Shape of MATRIX
MATRIX.shape
# دو بعد که هر کدوم 3 تا المان دارن 

torch.Size([2, 3])

In [24]:
# تعداد بعد ها 
MATRIX.ndim

2

In [28]:
# عنصر خاص از متغیر MATRIX 
MATRIX[0][1]
# بعد اول ، عنصر دوم :)

tensor(8)

In [43]:
# TENSOR
# تنژور 
TENSOR  = torch.tensor([
    [
        [1,2,3], [4,5,6], [7, 8, 9]
                         ]
                        ])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [30]:
# ndim 
TENSOR.ndim

3

In [31]:
TENSOR.shape

torch.Size([1, 3, 3])

تو بالا اولین عدد که میشه یک نشون میده ما یه فضا داریم (نشون دهنده ی اولین براکت ماست ) 
دومی ، عدد سه نشون میده 3 تا بعد داریم .
و سومی نشون بده هر کدوم از اون بعدا 3 تا المان دارن 

In [42]:
# تو نشون دادن براکت اولی از یک شروع میشه
# ولی موقع فراخوانی باید از صفر شروع کنیم :)
# میفهمم یکم عجیبه اما ترس نداره که یه گوگل کردن
# جیرینگی کارمونو راه میندازه:)
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
TENSOR[0][2]

tensor([7, 8, 9])

In [40]:
TENSOR[0][0:2]

tensor([[1, 2, 3],
        [4, 5, 6]])

### Random TENSORS


Why random tensors ?


Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those ransom numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> updarte random numbers 

In [48]:
# Creat a random tensor of size ( 3 ,4 )
# این تابع Torch 
# مقدار هایی بین -1 تا 1 تولید میکنه

random_tensor = torch.rand(3,4)
random_tensor 

tensor([[0.2707, 0.2638, 0.5171, 0.1333],
        [0.5510, 0.3518, 0.4719, 0.6379],
        [0.7899, 0.0707, 0.0462, 0.8104]])

In [49]:
random_tensor.ndim
# ndim SHORT of Number Dimintion

2

In [47]:
random_tensor.shape

torch.Size([3, 4])

In [58]:
random_tensor2 = torch.rand(3 , 2)
random_tensor2

tensor([[0.9403, 0.2953],
        [0.7502, 0.7200],
        [0.3764, 0.0237]])

In [59]:
random_tensor3 = torch.rand(10 ,10 , 10)
random_tensor3

tensor([[[0.0517, 0.5682, 0.2366, 0.9033, 0.0912, 0.9696, 0.3278, 0.9281,
          0.1515, 0.1455],
         [0.6149, 0.7858, 0.5255, 0.1136, 0.6335, 0.8139, 0.0484, 0.2180,
          0.8774, 0.4873],
         [0.5686, 0.3042, 0.1505, 0.8625, 0.0877, 0.0296, 0.5902, 0.9261,
          0.4437, 0.9188],
         [0.8258, 0.2118, 0.7822, 0.6434, 0.0265, 0.4162, 0.5944, 0.6497,
          0.6384, 0.0269],
         [0.3519, 0.0204, 0.2867, 0.5346, 0.2127, 0.3557, 0.4705, 0.7296,
          0.2652, 0.6078],
         [0.2105, 0.8663, 0.4922, 0.1979, 0.6248, 0.3468, 0.3130, 0.8909,
          0.0448, 0.2301],
         [0.3462, 0.9071, 0.8218, 0.1326, 0.2348, 0.8278, 0.4173, 0.1058,
          0.9067, 0.2835],
         [0.1930, 0.0876, 0.6951, 0.8051, 0.5779, 0.7579, 0.5511, 0.5286,
          0.9769, 0.6004],
         [0.7283, 0.9830, 0.8149, 0.2813, 0.2427, 0.6016, 0.3742, 0.3788,
          0.1887, 0.9752],
         [0.4523, 0.5858, 0.2411, 0.0317, 0.4942, 0.2574, 0.5136, 0.4538,
          0.1137,

In [54]:
# Creat a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size =(224 , 224 ,3 ))  # height  , width , color channel (Ex : Green , Red , Blue)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [55]:
# Size = 
# داخل تابع رند بودن یا نبودنش تاثیری نداره خروجی جفتشون یکیه :)

###  Zeros and Ones 

In [56]:
# Creat a tensor of all zeros
zeros  = torch.zeros(size=(3,2))
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [57]:
zeros * random_tensor

RuntimeError: ignored

In [61]:
# ضرب دوتا Tensor
zeros * random_tensor2

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [62]:
# Creat a tensor of all ones
ones = torch.ones(size=(3,2))
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [64]:
# Data type 
ones.dtype

torch.float32

### Creating a range of tensors and tensors_like

In [72]:
# Use torch.arange() 
one_to_ten = torch.arange(start=1,end=11)  #-->  میتونیم از start , end , step استفاده کنیم
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
# Creating tenosrs like 
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype
**Note=** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensor not right datatype

2. Tensor not rigth shape

3. Tensor not on the right device 

In [82]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0 , 4.0 ,6.0] ,
                               dtype=None ,
                               device = None ,           # By default is to bee "CPU"  / GPU is "cuda"
                               requires_grad= False)
float_32_tensor

tensor([3., 4., 6.])

In [77]:
float_32_tensor.dtype

torch.float32

In [83]:
# Float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)  # or float half
float_16_tensor

tensor([3., 4., 6.], dtype=torch.float16)

In [79]:
float_16_tensor.dtype

torch.float16